### PR TITLE
[WIP] Add license information and JS build process

### PR DESCRIPTION
**Pull request by nuest**
**please don't close this PR** yet, I'd just like to keep you updated. For completed/missing tasks see #5

### CODE REVIEW

**Comment by nuest** [comment]
Done. At least for now, as I am not completely happy with the license headers for the frontend project. I added grunt to automate the process, but the headers in the source files are not detected correctly.

Let me know what you guys think!

**Comment by bastrapp** [comment]
Looks great.

I could reproduce the header detection issue, though. I will wait with the merge until this is fixed.

A (late) question: having the header in each (small) source file: is that not creating a lot of overhead and is it necessary? Couldn't we just be providing packaged distribution files with one header instead of one header on each source file?

**Comment by nuest** [comment]
Yes, we could also package all the JavaScript in one file and just add a header to that one, it would also solve the duplicated headers (and since there are just a few files, I'd actually recommend to maintain their code headers manually).

I am no gradle expert though, but can look into it. Would you be OK with using gradle to create the distribution?

It suprised me (again!) how few tools and tutorials exists for managing licenses in the "JavaScript World". [Those script kiddies these days just don't care](http://www.theregister.co.uk/2013/04/18/github_licensing_study/) :-)

**Comment by bastrapp** [comment]
;-) ...

Never worked with gradle. If you recommend it, we can give it a shot. Is grunt becoming obsolete then? #lotsoftools

**Comment by nuest** [comment]
Sorry, my mistake - I of course ment grunt!

**Comment by bastrapp** [comment]
Would be great if you could establish a workflow to package (and minimize) the files.

**Comment by bslbckr** [comment]
Hi, I had a look at the changes made to the backend's build configuration. I think the PR is acceptable. We now have a effective check, wether or not the license hader is set for each single source-file. Otherwise the build fails. In addition `mvn license:format` is a convenient way to add or update the license header.

Good work, Daniel! :+1:

**Comment by nuest** [comment]
Ok - so the work on the backend seems complete (only will have to merge and update with the other developments, then re-run the license process).

Regarding the frontend, I'll try to make some progress this week. I changed to PR title to reflect this task and opened #22

**Comment by bastrapp** [comment]
Thank you

**Comment by nuest** [comment]
I'll close this PR in favour of #70 (which contains only the backend). A WIP PR for the frontend will follow later.

**Pull request closed without merging**
