### PR TITLE
Add contexts

### PR DESCRIPTION
**Pull request by bastrapp**
Added contexts to rosters and tournamentEditions. This way rosters can now adopt different policies for different associations, etc. Team registrations is now done via the roster (if not existing it will be created) and no longer the team, as we now allow for roster name additions to support "Team 2".

All changes in a list:
- Context class added
- Context property for Rosters and TournamentEditions
- Roster name addition to allow for Team 2, etc. to be included in one team entity
- Policy interface and DfvPolicy implementation added
- Test cases modified to work with new setup

### CODE REVIEW

**Comment by bastrapp** [comment]
After the merge there needs to be a short maintenance break where the teamRegistrations are moved from teams to rosters.

This query should do the job, once the DB is updated:

```
UPDATE TEAM_REGISTRATION tr2 SET roster = (
 SELECT r.id
 FROM ROSTER r
 LEFT JOIN TEAM t ON r.team = t.id
 LEFT JOIN (SELECT * FROM TEAM_REGISTRATION) tr ON tr.team = t.id
 LEFT JOIN DIVISION_REGISTRATION dr ON tr.division_registration = dr.id
 LEFT JOIN TOURNAMENT_EDITION te ON dr.tournament_edition = te.id
 WHERE dr.division_type = r.division_type
 AND dr.division_age = r.division_age
 AND te.season = r.season
 AND r.name_addition = ''
 AND tr.id = tr2.id);
```

**Comment by bslbckr** [comment]
we could incorporate the "small" update-statement into a liquibase-change. This way, everything would be contained in the git-repository and we could use our approved db-update routine :)

**Comment by bslbckr** [comment]
That''s the mentioned change: http://www.liquibase.org/documentation/changes/sql.html

**Comment by bastrapp** [comment]
Alright, it's in. I did not remove the team property yet for safety reasons: if the transform from team to roster registration is not working, information would be lost

**Comment by bastrapp** [comment]
I forgot to mention that this PR tackles #24

**Pull request merged**
